// Chain logos — used by UNIVERSE_CHAIN_INFO / getChainInfo
export const ALL_NETWORKS_LOGO = require('./logos/png/all-networks-icon.png')
export const ETHEREUM_LOGO = require('./logos/png/ethereum-logo.png')
export const OPTIMISM_LOGO = require('./logos/png/optimism-logo.png')
export const ARBITRUM_LOGO = require('./logos/png/arbitrum-logo.png')
export const BASE_LOGO = require('./logos/png/base-logo.png')
export const BNB_LOGO = require('./logos/png/bnb-logo.png')
export const MONAD_LOGO_FILLED = require('./logos/png/monad-logo-filled.png')
export const POLYGON_LOGO = require('./logos/png/polygon-logo.png')
export const BLAST_LOGO = require('./logos/png/blast-logo.png')
export const AVALANCHE_LOGO = require('./logos/png/avalanche-logo.png')
export const CELO_LOGO = require('./logos/png/celo-logo.png')
export const WORLD_CHAIN_LOGO = require('./logos/png/world-chain-logo.png')
export const ZORA_LOGO = require('./logos/png/zora-logo.png')
export const ZKSYNC_LOGO = require('./logos/png/zksync-logo.png')
export const LINEA_LOGO = require('./logos/png/linea-logo.png')
export const SOLANA_LOGO = require('./logos/png/solana-logo.png')
export const SONEIUM_LOGO = require('./logos/png/soneium-logo.png')
export const TEMPO_LOGO = require('./logos/png/tempo-logo.png')
export const XLAYER_LOGO = require('./logos/png/xlayer-logo.png')
export const OKB_LOGO = require('./logos/png/okb-logo.png')
export const UNICHAIN_LOGO = require('./logos/png/unichain-logo.png')
export const UNICHAIN_SEPOLIA_LOGO = require('./logos/png/unichain-sepolia-logo.png')
export const ETH_LOGO = require('./logos/png/eth-logo.png')

// Token logos — bundled locally so the IPFS build makes no third-party
// image requests. Used by the static SPXSwap token list (spxTokens.ts).
export const DAI_LOGO = require('./logos/png/dai-logo.png')
export const SPX6900_LOGO = require('./logos/png/spx6900-logo.png')
export const USDC_LOGO = require('./logos/png/usdc-logo.png')
export const USDT_LOGO = require('./logos/png/usdt-logo.png')
export const WBTC_LOGO = require('./logos/png/wbtc-logo.png')
export const WETH_LOGO = require('./logos/png/weth-logo.png')

// Unitag icons — used by ui/src/components/icons/Unitag.tsx
export const UNITAG_DARK = require('./graphics/unitag-dark.png')
export const UNITAG_LIGHT = require('./graphics/unitag-light.png')
export const UNITAG_DARK_SMALL = require('./graphics/unitag-dark-small.png')
export const UNITAG_LIGHT_SMALL = require('./graphics/unitag-light-small.png')
